language: rust
rust:
- stable
- beta
- nightly
matrix:
  - os: linux
    before_deploy:
      - mv target/release/tacho target/release/tacho-$TRAVIS_TAG-$TRAVIS_OS_NAME
  - os: osx
    before_deploy:
      - mv target/release/tacho target/release/tacho-$TRAVIS_TAG-$TRAVIS_OS_NAME
  - os: windows
    before_deploy:
      - rename target/release/tacho.exe target/release/tacho-$TRAVIS_TAG-$TRAVIS_OS_NAME.exe

  allow_failures:
  - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --release
os:
- linux
- osx
- windows

# rename before deployment
# before_deploy:
#  - mv target/release/tacho target/release/tacho-$TRAVIS_TAG-$TRAVIS_OS_NAME
    
deploy:
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_RUST_VERSION = stable"
      branch: master
    file:
      - target/release/tacho-$TRAVIS_TAG-$TRAVIS_OS_NAME
    api_key: $SecToken
