language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --release
os:
- linux
- osx

before_deploy:
  - mv target/release/tacho "target/release/tacho-$TRAVIS_TAG-$TRAVIS_OS_NAME"
deploy:
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_RUST_VERSION = stable"
      branch: master
    file:
      - target/release/tacho-*
    api_key: $SecToken
