language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --release
os:
- linux
- osx
- windows

# rename before deployment
before_deploy:
  - mv target/release/tacho target/release/tacho-$TRAVIS_TAG-$TRAVIS_OS_NAME
    on:
      os: linux

  - mv target/release/tacho target/release/tacho-$TRAVIS_TAG-$TRAVIS_OS_NAME
    on:
      os: osx

  - rename target/release/tacho.exe target/release/tacho-$TRAVIS_TAG-$TRAVIS_OS_NAME.exe
    on:
      os: windows

deploy:
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_RUST_VERSION = stable"
      branch: master
    file:
      - target/release/tacho-$TRAVIS_TAG-$TRAVIS_OS_NAME
    api_key: $SecToken
