language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --release
os:
- linux
- osx
- windows

# rename before deployment
before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then mv target/release/tacho target/release/tacho-$TRAVIS_TAG-$TRAVIS_OS_NAME; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then mv target/release/tacho target/release/tacho-$TRAVIS_TAG-$TRAVIS_OS_NAME; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then rename target/release/tacho target/release/tacho-$TRAVIS_TAG-$TRAVIS_OS_NAME; fi

deploy:
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_RUST_VERSION = stable"
      branch: master
    file:
      - target/release/tacho-$TRAVIS_TAG-$TRAVIS_OS_NAME
    api_key: $SecToken
