language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- linux
- osx
- windows
before_deploy:
  - mv target/release/tacho "target/release/tacho-$TRAVIS_TAG-$TRAVIS_OS_NAME"
deploy:
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_RUST_VERSION = stable"
      branch: master
    file:
      - target/release/tacho-*
    api_key:
      secure: 1e2448c8eaed008079f0cc5f5f6c9d24e11a946d 
